export const STOCKS = [
  "AAPL",
  "MSFT",
  "NVDA",
  "GOOGL",
  "META",
  "JPM",
  "GS",
  "BAC",
  "JNJ",
  "PFE",
  "UNH",
  "MCD",
  "NKE",
  "KO",
  "MMM",
  "CAT",
  "DAL",
  "XOM",
  "CVX",
  "HAL",
] as const;

export const STOCK_SECTOR_MAP: Record<string, string> = {
  AAPL: "Technology",
  MSFT: "Technology",
  NVDA: "Technology",
  GOOGL: "Technology",
  META: "Technology",
  JPM: "Financials",
  GS: "Financials",
  BAC: "Financials",
  JNJ: "Healthcare",
  PFE: "Healthcare",
  UNH: "Healthcare",
  MCD: "Consumer",
  NKE: "Consumer",
  KO: "Consumer",
  MMM: "Industrials",
  CAT: "Industrials",
  DAL: "Industrials",
  XOM: "Energy",
  CVX: "Energy",
  HAL: "Energy",
};
